==== The plugin configuration

The plugin does not have general configuration.

On the health page, a test to check the https in external connection is done. It is not possible  to use a self-signed certificate.

Un certificat letsencrypt fonctionne (en ayant bien paramétrer le certificat de chaine également)

==== Configuration of equipment

Chaque équipement correspond à un Bot telegram

So you must get the key supplied by Telegram to the creation of the bot on the equipment page

Vous pouvez configurer le bot pour créer des notifications silencieuses sur les téléphones

Il est possible de personnaliser le texte que le bot répond à un message et le format par défaut des messages du bot

Vous pouvez également préciser un emplacement pour stocker les fichiers envoyés au bot. Dans ce cas les fichiers seront créés suivant le format :

- vidéo : $username.mp4

- photo : $username.png

- document : nom du fichier envoyé

Par la suite, les utilisateurs entrant en communication avec le bot créeront automatiquement une entrée sur l'équipement pour envoyer des messages si l'option est activée

Pareil pour les groupes et le ask marche sur les groupes (il ne marche pas pour le destinataire "Tous")

==== Envoyer des messages

Les commandes actions permettent d'envoyer des messages. Il est possible de fournir des options pour les messages

- tts : la valeur doit être le chemin d'un fichier audio de type ogg encodé avec opus qui sera notifié en message vocal dans Telegram (sinon un texte mais opus-tools doit être installé)

- location : la valeur doit être soit une commande geoloc soit "latitude,longitude"

- file : la valeur doit être le path d'un ou plusieurs fichiers

- message : permet d'envoyer un message dans le même ordre

- notify : valeur binaire pour que la notif soit silencieuse (0) ou avec son/vibrationn (1)

- parse_mode : format du message envoyé (correspon à l'option de conf équipement), valeurs possibles : '', HTML, Markdown

Exemple : tts=/fichier.ogg message=detection file=/screen1.png,/screen2.png notify=0

Toutes les pièces jointes ajoutées à une commande action sont envoyées avec un type détecté par rapport à leur extension :

- vidéos en extensions "avi,mpeg,mpg,mkv,mp4,mpe"

- audio en extensions "ogg,mp3"

- images en extensions "gif,jpeg,jpg,png"

- le reste est envoyé en tant que document joint