==== Configuration du plugin

Le plugin ne comporte pas de configuration générale.

Sur la page santé, un test pour vérifier le https en connexion externe est fait. Il n'est pas possible en l'état d'utiliser un certificat autosigné.

Un certification letsencrypt fonctionne (en ayant bien paramétrer le certificat de chaine également)

==== Configuration d'un équipement

Chaque équipement correspond à un Bot telegram

Vous devez donc rentrer la clef fournie par Telegram à la création du bot sur la page équipement

Vous pouvez configurer le bot pour créer des notifications silencieuses sur les téléphones

Il est possible de personnaliser le texte que le bot répond à un message

Vous pouvez également préciser un emplacement pour stocker les fichiers envoyés au bot. Dans ce cas les fichiers seront créés suivant le format :

- vidéo : $username.mp4

- photo : $username.png

- document : nom du fichier envoyé

Par la suite, les utilisateurs entrant en communication avec le bot créeront automatiquement une entrée sur l'équipement pour envoyer des messages

Pareil pour les groupes et le ask marche sur les groupes

==== Envoyer des messages

Par défaut, pour une commande action il est possible de faire les types d'envoi :

- tts : en précisant "tts" en titre, le message doit être le chemin d'un fichier audio de type ogg encodé avec opus qui sera notifié en message vocal dans Telegram (sinon un texte mais opus-tools doit être installé)

- location : en précisant "location" en titre, le message doit être soit "geoloc:idEqGeoloc" soit "latitude,longitude"

- file : en précisant "file" en titre, le message doit être le path d'un fichier

- texte dans le reste des cas

Toutes les pièces jointes ajoutées à une commande action sont envoyées :

- vidéos en extensions "avi,mpeg,mpg,mkv,mp4,mpe"

- audio en extensions "ogg,mp3"

- images en extensions "gif,jpeg,jpg,png"

- le reste est envoyé en tant que document joint
